#!/bin/sh

USER="id -un"
LOGNAME=$USER
PS1='\u@\h:\w\$ '
HOSTNAME='/bin/hostname'

PATH=/bin:/sbin:/usr/bin:/usr/sbin
LD_LIBRARY_PATH=/lib:/lib64:/usr/lib:/usr/lib64

export USER LOGNAME PS1 PATH LD_LIBRARY_PATH